###
GET http://127.0.0.1:5000/books HTTP/1.1
content-type: application/json


###
POST http://127.0.0.1:5000/books HTTP/1.1
content-type: application/json

{
    "author": "me",
    "name": "mybook",
    "publisher": "asd"
}

###
PUT http://127.0.0.1:5000/books/4 HTTP/1.1
content-type: application/json

{
    "author": "NathanHughes",
    "name": "tasdfasdfesddt",
    "publisher": "jeff"
}

###
DELETE http://127.0.0.1:5000/books/45 HTTP/1.1